/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router
// It will be regenerated when you run `npm run dev`

import { createFileRoute, createRootRouteWithContext } from "@tanstack/react-router";

// Import route components
import { Route as RootRoute } from "./routes/__root";
import { Route as IndexRoute } from "./routes/index";
import { Route as LoginRoute } from "./routes/login";
import { Route as SignupRoute } from "./routes/signup";
import { Route as AuthedRoute } from "./routes/_authed";
import { Route as BrowseIndexRoute } from "./routes/_authed/browse/index";
import { Route as BrowseCategoryRoute } from "./routes/_authed/browse/$category";
import { Route as GuidelineSlugRoute } from "./routes/_authed/guideline/$slug";
import { Route as AssetsIndexRoute } from "./routes/_authed/assets/index";
import { Route as ChatIndexRoute } from "./routes/_authed/chat/index";
import { Route as AdminIndexRoute } from "./routes/_authed/admin/index";
import { Route as AdminGuidelinesRoute } from "./routes/_authed/admin/guidelines";
import { Route as AdminUsersRoute } from "./routes/_authed/admin/users";

// Create the route tree
declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRoute;
      parentRoute: typeof RootRoute;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRoute;
      parentRoute: typeof RootRoute;
    };
    "/signup": {
      id: "/signup";
      path: "/signup";
      fullPath: "/signup";
      preLoaderRoute: typeof SignupRoute;
      parentRoute: typeof RootRoute;
    };
    "/_authed": {
      id: "/_authed";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthedRoute;
      parentRoute: typeof RootRoute;
    };
    "/_authed/browse/": {
      id: "/_authed/browse/";
      path: "/browse";
      fullPath: "/browse";
      preLoaderRoute: typeof BrowseIndexRoute;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/browse/$category": {
      id: "/_authed/browse/$category";
      path: "/browse/$category";
      fullPath: "/browse/$category";
      preLoaderRoute: typeof BrowseCategoryRoute;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/guideline/$slug": {
      id: "/_authed/guideline/$slug";
      path: "/guideline/$slug";
      fullPath: "/guideline/$slug";
      preLoaderRoute: typeof GuidelineSlugRoute;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/assets/": {
      id: "/_authed/assets/";
      path: "/assets";
      fullPath: "/assets";
      preLoaderRoute: typeof AssetsIndexRoute;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/chat/": {
      id: "/_authed/chat/";
      path: "/chat";
      fullPath: "/chat";
      preLoaderRoute: typeof ChatIndexRoute;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/admin/": {
      id: "/_authed/admin/";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AdminIndexRoute;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/admin/guidelines": {
      id: "/_authed/admin/guidelines";
      path: "/admin/guidelines";
      fullPath: "/admin/guidelines";
      preLoaderRoute: typeof AdminGuidelinesRoute;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/admin/users": {
      id: "/_authed/admin/users";
      path: "/admin/users";
      fullPath: "/admin/users";
      preLoaderRoute: typeof AdminUsersRoute;
      parentRoute: typeof AuthedRoute;
    };
  }
}

// Build the route tree
export const routeTree = RootRoute.addChildren([
  IndexRoute,
  LoginRoute,
  SignupRoute,
  AuthedRoute.addChildren([
    BrowseIndexRoute,
    BrowseCategoryRoute,
    GuidelineSlugRoute,
    AssetsIndexRoute,
    ChatIndexRoute,
    AdminIndexRoute,
    AdminGuidelinesRoute,
    AdminUsersRoute,
  ]),
]);

/* prettier-ignore-end */
