/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedSearchRouteImport } from './routes/_authed/search'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedBrowseIndexRouteImport } from './routes/_authed/browse/index'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedGuidelineSlugRouteImport } from './routes/_authed/guideline/$slug'
import { Route as AuthedBrowseCategoryRouteImport } from './routes/_authed/browse/$category'
import { Route as AuthedAdminUsersRouteImport } from './routes/_authed/admin/users'
import { Route as AuthedAdminNotificationsRouteImport } from './routes/_authed/admin/notifications'
import { Route as AuthedAdminGuidelinesRouteImport } from './routes/_authed/admin/guidelines'
import { Route as AuthedAdminDocumentsRouteImport } from './routes/_authed/admin/documents'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSearchRoute = AuthedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBrowseIndexRoute = AuthedBrowseIndexRouteImport.update({
  id: '/browse/',
  path: '/browse/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedGuidelineSlugRoute = AuthedGuidelineSlugRouteImport.update({
  id: '/guideline/$slug',
  path: '/guideline/$slug',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBrowseCategoryRoute = AuthedBrowseCategoryRouteImport.update({
  id: '/browse/$category',
  path: '/browse/$category',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminUsersRoute = AuthedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminNotificationsRoute =
  AuthedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminGuidelinesRoute = AuthedAdminGuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminDocumentsRoute = AuthedAdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthedAdminRouteWithChildren
  '/search': typeof AuthedSearchRoute
  '/settings': typeof AuthedSettingsRoute
  '/admin/documents': typeof AuthedAdminDocumentsRoute
  '/admin/guidelines': typeof AuthedAdminGuidelinesRoute
  '/admin/notifications': typeof AuthedAdminNotificationsRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/browse/$category': typeof AuthedBrowseCategoryRoute
  '/guideline/$slug': typeof AuthedGuidelineSlugRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/browse': typeof AuthedBrowseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/search': typeof AuthedSearchRoute
  '/settings': typeof AuthedSettingsRoute
  '/admin/documents': typeof AuthedAdminDocumentsRoute
  '/admin/guidelines': typeof AuthedAdminGuidelinesRoute
  '/admin/notifications': typeof AuthedAdminNotificationsRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/browse/$category': typeof AuthedBrowseCategoryRoute
  '/guideline/$slug': typeof AuthedGuidelineSlugRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/browse': typeof AuthedBrowseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/admin': typeof AuthedAdminRouteWithChildren
  '/_authed/search': typeof AuthedSearchRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/admin/documents': typeof AuthedAdminDocumentsRoute
  '/_authed/admin/guidelines': typeof AuthedAdminGuidelinesRoute
  '/_authed/admin/notifications': typeof AuthedAdminNotificationsRoute
  '/_authed/admin/users': typeof AuthedAdminUsersRoute
  '/_authed/browse/$category': typeof AuthedBrowseCategoryRoute
  '/_authed/guideline/$slug': typeof AuthedGuidelineSlugRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/browse/': typeof AuthedBrowseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/search'
    | '/settings'
    | '/admin/documents'
    | '/admin/guidelines'
    | '/admin/notifications'
    | '/admin/users'
    | '/browse/$category'
    | '/guideline/$slug'
    | '/admin/'
    | '/browse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/search'
    | '/settings'
    | '/admin/documents'
    | '/admin/guidelines'
    | '/admin/notifications'
    | '/admin/users'
    | '/browse/$category'
    | '/guideline/$slug'
    | '/admin'
    | '/browse'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/admin'
    | '/_authed/search'
    | '/_authed/settings'
    | '/_authed/admin/documents'
    | '/_authed/admin/guidelines'
    | '/_authed/admin/notifications'
    | '/_authed/admin/users'
    | '/_authed/browse/$category'
    | '/_authed/guideline/$slug'
    | '/_authed/admin/'
    | '/_authed/browse/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/search': {
      id: '/_authed/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthedSearchRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/browse/': {
      id: '/_authed/browse/'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AuthedBrowseIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/guideline/$slug': {
      id: '/_authed/guideline/$slug'
      path: '/guideline/$slug'
      fullPath: '/guideline/$slug'
      preLoaderRoute: typeof AuthedGuidelineSlugRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/browse/$category': {
      id: '/_authed/browse/$category'
      path: '/browse/$category'
      fullPath: '/browse/$category'
      preLoaderRoute: typeof AuthedBrowseCategoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/users': {
      id: '/_authed/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthedAdminUsersRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/notifications': {
      id: '/_authed/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthedAdminNotificationsRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/guidelines': {
      id: '/_authed/admin/guidelines'
      path: '/guidelines'
      fullPath: '/admin/guidelines'
      preLoaderRoute: typeof AuthedAdminGuidelinesRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/documents': {
      id: '/_authed/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthedAdminDocumentsRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminDocumentsRoute: typeof AuthedAdminDocumentsRoute
  AuthedAdminGuidelinesRoute: typeof AuthedAdminGuidelinesRoute
  AuthedAdminNotificationsRoute: typeof AuthedAdminNotificationsRoute
  AuthedAdminUsersRoute: typeof AuthedAdminUsersRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminDocumentsRoute: AuthedAdminDocumentsRoute,
  AuthedAdminGuidelinesRoute: AuthedAdminGuidelinesRoute,
  AuthedAdminNotificationsRoute: AuthedAdminNotificationsRoute,
  AuthedAdminUsersRoute: AuthedAdminUsersRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedSearchRoute: typeof AuthedSearchRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedBrowseCategoryRoute: typeof AuthedBrowseCategoryRoute
  AuthedGuidelineSlugRoute: typeof AuthedGuidelineSlugRoute
  AuthedBrowseIndexRoute: typeof AuthedBrowseIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedSearchRoute: AuthedSearchRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedBrowseCategoryRoute: AuthedBrowseCategoryRoute,
  AuthedGuidelineSlugRoute: AuthedGuidelineSlugRoute,
  AuthedBrowseIndexRoute: AuthedBrowseIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
